name: BetterSkyBlock
main: com.fnv_tw.BetterSkyBlock
version: 0.0.1
api-version: '1.18'
author: https://github.com/cool9850311
depend: [Multiverse-Core]
commands:
  BetterSkyBlockIsland:
    description: "Main command of BetterSkyBlock"
    aliases: [is]
    permission: betterskyblock.usage
  AdminIslandCommand:
    description: "Commands for admin only"
    aliases: [isadmin]
    permission: betterskyblock.admin
permissions:
  betterskyblock.*:
    description: "All BetterSkyBlock permissions"
    default: op
    children:
      betterskyblock.usage: true
  betterskyblock.admin:
    description: "Admin Permission"
  betterskyblock.usage:
    description: "Permission to use /is"
  betterskyblock.fly:
    description: "Permission to fly on island"
  betterskyblock.bypass.fly:
    description: "Permission to bypass fly action on island"