name: BetterSkyBlock
main: com.fnv_tw.BetterSkyBlock
version: 0.0.1
api-version: '1.17'
depend: [Multiverse-Core]
commands:
  BetterSkyBlockIsland:
    description: "Main command of BetterSkyBlock"
    aliases: [is]
  AdminIslandCommand:
    description: "Commands for admin only"
    aliases: [isadmin]
permissions:
  betterskyblock.*:
    description: "All coin shop permissions"
    default: op
    children:
      betterskyblock.usage: true
  betterskyblock.admin:
    description: "Admin Permission"
  betterskyblock.usage:
    description: "Permission to use /is"